"""Add company_id to InterestedCampaigns

Revision ID: 788a5e23b99f
Revises: a0dc0e85d3b2
Create Date: 2024-08-09 08:22:28.856376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '788a5e23b99f'
down_revision = 'a0dc0e85d3b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interested_campaigns', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'company', ['company_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interested_campaigns', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('company_id')

    # ### end Alembic commands ###
